### PR TITLE
Aprroval improvements

### PR DESCRIPTION
**Pull request by Ahnaf-Abid-Hossain**
css improvements, meeting notes only for admin, and some other stuff

### CODE REVIEW

**Comment by Ahnaf-Abid-Hossain** [comment]
Approval- needed, fixed the merge conflicts

**Comment by parkerjacob37** [comment]
Looks like there's still a failing test case for meeting notes. Could you fix that before merging so we keep our dev branch as functional as possible?

**Comment by Ahnaf-Abid-Hossain** [comment]
Committed the fixed test cases, was caused by removing some lines in user.html.erb that was doing privacy checks and another one was a test case in meeting notes that was looking for user id being showed but I had removed that feature.

**Review by parkerjacob37 — APPROVED** [review]
Everything passes now, and is functional. Approved.

**Pull request merged**
