### PR TITLE
Update <title> of site from 'Week3Lab' to 'Association of Baptist Students' Alumni Directory'

### PR DESCRIPTION
**Pull request by jamsterwes**
Oops we haven't updated the title since we made this starter code in Week 3 Lab.

### CODE REVIEW

**Comment by jamsterwes** [comment]
Passes rspec and rubocop.

**Comment by parkerjacob37** [comment]
This looks good, thanks for catching that Wes

**Review by parkerjacob37 — APPROVED** [review]
Code is reviewed.

**Comment by jamsterwes** [comment]
idk how a change to `db/schema.rb` got put into this lol, let me remove that then this can go straight to test and main

**Comment by jamsterwes** [comment]
> idk how a change to `db/schema.rb` got put into this lol, let me remove that then this can go straight to test and main

i honestly think this is fine, gonna push

**Pull request merged**
