### PR TITLE
Added Quick Links feature (MVP)

### PR DESCRIPTION
**Pull request by jamsterwes**

### CODE REVIEW

**Comment by jamsterwes** [comment]
Not even close to done yet

**Comment by jamsterwes** [comment]
Passing rubocop and rspec, CRUD pages need redesign/cleaning up but other than that the functionality is there.

**Comment by jamsterwes** [comment]
Consider this to be SCRUM-42, SCRUM-51, and SCRUM-39

Making it better looking (SCRUM-54) can come later.
Making update (SCRUM-40) is not done until links can be properly reordered (up/down buttons in a list).

**Review by parkerjacob37 — APPROVED** [review]
Looks good, can be merged with dev.

**Pull request merged**
