### PR TITLE
[post-review] New navbar styling

### PR DESCRIPTION
**Pull request by jamsterwes**
(awaiting customer approval)
image

### CODE REVIEW

**Comment by jamsterwes** [comment]
image
Tests pass locally, runner failure appears to be issue with docker registry...
image
Will make dummy commit later to verify that tests still pass on runner.

**Comment by jamsterwes** [comment]
Okay tests passing, we can code review this but I would wait until customer approves scope list before merging... I simply did this before his response because its a 2 second fix.

**Comment by jamsterwes** [comment]
Merge conflicts with links_spec and latest PR, kept this branch's changes due to test case rewrite.

**Review by parkerjacob37 — APPROVED** [review]
Let's get this money. Approved.

**Pull request merged**
