### PR TITLE
[SCRUM-40] Edit/reorder Links as an admin

### PR DESCRIPTION
**Pull request by jamsterwes**

### CODE REVIEW

**Comment by jamsterwes** [comment]
(not finished yet)

**Comment by jamsterwes** [comment]
Ready for code review pending rspec, etc...

**Comment by parkerjacob37** [comment]
Hey Wes, could we delete those commented out lines in spec/rails_helper.rb? Just to keep the code a little cleaner.

**Comment by jamsterwes** [comment]
> Hey Wes, could we delete those commented out lines in spec/rails_helper.rb? Just to keep the code a little cleaner.

fixed in latest commit

**Review by parkerjacob37 — APPROVED** [review]
Thanks for changing that. Approved.

**Pull request merged**
